{"faultCode":1,"faultString":"Traceback (most recent call last):\n  File \"\/opt\/openerp\/odoo12ent\/odoo\/odoo\/addons\/base\/controllers\/rpc.py\", line 63, in xmlrpc_2\n    response = self._xmlrpc(service)\n  File \"\/opt\/openerp\/odoo12ent\/odoo\/odoo\/addons\/base\/controllers\/rpc.py\", line 43, in _xmlrpc\n    result = dispatch_rpc(service, method, params)\n  File \"\/opt\/openerp\/odoo12ent\/odoo\/odoo\/http.py\", line 120, in dispatch_rpc\n    result = dispatch(method, params)\n  File \"\/opt\/openerp\/odoo12ent\/odoo\/odoo\/service\/model.py\", line 39, in dispatch\n    res = fn(db, uid, *params)\n  File \"\/opt\/openerp\/odoo12ent\/odoo\/odoo\/service\/model.py\", line 153, in execute_kw\n    return execute(db, uid, obj, method, *args, **kw or {})\n  File \"\/opt\/openerp\/odoo12ent\/odoo\/odoo\/service\/model.py\", line 97, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"\/opt\/openerp\/odoo12ent\/odoo\/odoo\/service\/model.py\", line 160, in execute\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\n  File \"\/opt\/openerp\/odoo12ent\/odoo\/odoo\/service\/model.py\", line 149, in execute_cr\n    return odoo.api.call_kw(recs, method, args, kw)\n  File \"\/opt\/openerp\/odoo12ent\/odoo\/odoo\/api.py\", line 745, in call_kw\n    return _call_kw_model(method, model, args, kwargs)\n  File \"\/opt\/openerp\/odoo12ent\/odoo\/odoo\/api.py\", line 718, in _call_kw_model\n    result = method(recs, *args, **kwargs)\n  File \"\/opt\/openerp\/odoo12ent\/odoo\/odoo\/models.py\", line 4510, in search_read\n    records = self.search(domain or [], offset=offset, limit=limit, order=order)\n  File \"\/opt\/openerp\/odoo12ent\/odoo\/odoo\/models.py\", line 1556, in search\n    res = self._search(args, offset=offset, limit=limit, order=order, count=count)\n  File \"\/opt\/openerp\/odoo12ent\/odoo\/odoo\/models.py\", line 4064, in _search\n    self._cr.execute(query_str, where_clause_params)\n  File \"\/opt\/openerp\/odoo12ent\/odoo\/odoo\/sql_db.py\", line 148, in wrapper\n    return f(self, *args, **kwargs)\n  File \"\/opt\/openerp\/odoo12ent\/odoo\/odoo\/sql_db.py\", line 225, in execute\n    res = self._obj.execute(query, params)\npsycopg2.errors.InvalidTextRepresentation: invalid input syntax for integer: \"\"\nLINE 1: ...yee\".\"active\" = true)  AND  (\"hr_employee\".\"id\" = '')) ORDER...\n                                                             ^\n\n"}